Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.hostname = "webserver"
    web.vm.network "private_network", ip: "192.168.44.101"

    web.vm.provider "virtualbox" do |vb|
      vb.name = "vm-devops-j1-test"
      vb.memory = "1024"
      vb.cpus = 2
    end
    web.vm.synced_folder "./site", "/var/www/html"
    web.vm.provision "shell", path:"install.sh"
  end


  config.vm.define "bd" do |bd|
    bd.vm.box = "ubuntu/bionic64"
    bd.vm.hostname = "webserver"
    bd.vm.network "private_network", ip: "192.168.44.102"

    bd.vm.provider "virtualbox" do |vb|
      vb.name = "vm-base-de-donnee"
      vb.memory = "1024"
      vb.cpus = 2
    end
    bd.vm.synced_folder "./site", "/var/www/html"
    bd.vm.provision "shell", path:"installbd.sh"
  end

end
