- name: install prerequisite
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  tags:
    - install
    - docker

- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - install
    - docker

- name: add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
    filename: docker
    update_cache: yes
  tags:
    - install
    - docker

- name: install docker and docker-compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  tags:
    - install
    - docker

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - start_services
    - docker

- name: Add user to docker group
  user:
    name: "{{ ansible_user}}"
    groups: docker
    append: yes

- name: Create jenkins directory
  file:
    path: /opt/jenkins
    state: directory
    mode: "0755"

- name: copy docker compose file
  copy:
    src: docker-compose.yml
    dest: /opt/jenkins/docker-compose.yml
    mode: "0644"

- name:
  copy:
    src: Dockerfile
    dest: /opt/jenkins/Dockerfile
    mode: "0644"

- name: build and start jenkins containerd
  command: docker compose up -d --build
  args:
    chdir: /opt/jenkins
