
Vagrant.configure("2") do |config|

  # === Controlleur ===
  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/bionic64"
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.44.100"

    controller.vm.provider "virtualbox" do |vb|
      vb.name = "controller"
      vb.memory = "512"
      vb.cpus = 1
    end
    controller.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get upgrade -y
      sudo apt install ansible -y
      SHELL
    controller.vm.synced_folder ".vagrant/machines/web/virtualbox", "/keys/web"
    controller.vm.synced_folder ".vagrant/machines/jenkins/virtualbox", "/keys/jenkins"
    controller.vm.synced_folder "playbooks/", "/playbooks", mount_options: ["dmode=755", "fmode=644"]
  end

# === web ===
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.44.101"

    web.vm.provider "virtualbox" do |vb|
      vb.name = "web"
      vb.memory = "1024"
      vb.cpus = 1
    end
  web.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update && sudo apt-get upgrade -y
     sudo apt install python -y
    SHELL
  end
# jenkins 
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/bionic64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.44.102"

    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
      vb.memory = "2048"
      vb.cpus = 2
    end
    jenkins.vm.synced_folder ".vagrant/machines/web/virtualbox", "/keys/web"
    jenkins.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update && sudo apt-get upgrade -y
     sudo apt install python -y
    SHELL
  end
end
