
Vagrant.configure("2") do |config|

  # === ansible ===
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "ubuntu/bionic64"
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.56.30"

    ansible.vm.provider "virtualbox" do |vb|
      vb.name = "vm-ansible"
      vb.memory = "1024"
      vb.cpus = 1
    end
    ansible.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get upgrade -y
      sudo apt install ansible -y
      SHELL
      ansible.vm.synced_folder ".vagrant/machines/apache/virtualbox", "/keys/apache"
      ansible.vm.synced_folder ".vagrant/machines/jenkins/virtualbox", "/keys/jenkins"
      ansible.vm.synced_folder "playbooks/", "/playbooks", mount_options: ["dmode=755", "fmode=644"]
  end

# === apache ===
  config.vm.define "apache" do |apache|
    apache.vm.box = "ubuntu/bionic64"
    apache.vm.hostname = "apache"
    apache.vm.network "private_network", ip: "192.168.56.20"

    apache.vm.provider "virtualbox" do |vb|
      vb.name = "vm-apache"
      vb.memory = "1024"
      vb.cpus = 1
    end
    apache.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update && sudo apt-get upgrade -y
     sudo apt install python -y
    SHELL
  end
  
# jenkins 
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/bionic64"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.56.10"

    jenkins.vm.provider "virtualbox" do |vb|
      vb.name = "vm-jenkins"
      vb.memory = "2048"
      vb.cpus = 2
    end
    jenkins.vm.synced_folder ".vagrant/machines/apache/virtualbox", "/keys/apache"
    jenkins.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update && sudo apt-get upgrade -y
     sudo apt install python -y
    SHELL
  end
end
