version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /keys/apache/private_key:/var/jenkins_home/.ssh/apache_key:ro

    restart: unless-stopped

volumes:
  jenkins_home:
