Vagrant.configure("2") do |config|

  config.vm.define "controller" do |controller|
    controller.vm.box = "ubuntu/bionic64"
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.44.101"

    controller.vm.provider "virtualbox" do |vb|
      vb.name = "controller"
      vb.memory = "1024"
      vb.cpus = 1
    end
    controller.vm.synced_folder ".vagrant/machines/worker/virtualbox", "/home/worker"
    controller.vm.synced_folder "playbooks/site", "/home/vagrant/ansibletest/playbooks"
    controller.vm.provision "shell", path:"controller.sh"
  end


  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.hostname = "webserver"
    worker.vm.network "private_network", ip: "192.168.44.102"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "worker"
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", path:"worker.sh"
  end

end
